FROM node:lts-alpine as builder


WORKDIR /src

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginxinc/nginx-unprivileged

USER root

COPY config/nginx.prod.config /etc/nginx/conf.d/default.conf

COPY --chown=nginx:nginx --from=builder /src/dist /dist

EXPOSE 80

USER 101